### PR TITLE
Update data-sources.html.md.erb

### PR DESCRIPTION
**Pull request by Hyacinthe-Jacquet**
Not sure what that character was there for...
Since 2.7

### CODE REVIEW

**Comment by mjgutermuth** [comment]
Hi @Hyacinthe-Jacquet! Please take a look at the comment above to authorize your commit.

**Comment by Hyacinthe-Jacquet** [comment]
> Hi @Hyacinthe-Jacquet! Please take a look at the comment above to authorize your commit.

I'm not trying to contribute content to the documentation. I just raised here that you have a typo (an unintended character to be exact) in the documentation. Feel free to fix it.

**Comment by mjgutermuth** [comment]
Appreciated! The CF Foundation considers any PR to be a contribution, and they require us to have CLA confirmation before we are allowed to merge anything. I would go ahead and make the change on my end, but for some reason I'm not seeing the unintended character you mentioned. Can you tell me what you're seeing?

**Comment by animatedmax** [comment]
Removing all unicode characters in this repository. https://www.pivotaltracker.com/story/show/180348866

**Pull request closed without merging**
